export const itemMsg = {
    "d": {
        "name": "德育素质",
        "limit": "10",
        "apply": false,
        "module": 1,
    },

    "d1": {
        "name": "—基本评定分D1",
        "limit": 6,
        "apply": false,
        "module": 1,
    },
    "d2": {
        "name": "—记实加减分D2",
        "limit": 4,
        "apply": false,
        "module": 1,
    },
    "d21": {
        "name": "——集体评定等级分",
        "limit": 1,
        "apply": true,
        "module": 1,
    },
    "d22": {
        "name": "——社会责任记实分",
        "limit": 2,
        "apply": true,
        "module": 1,
    },
    "d23": {
        "name": "——思政学习加减分",
        "limit": 1,
        "apply": false,
        "module": 1,
    },
    "d24": {
        "name": "——违纪违规扣分",
        "limit": 1e6,
        "apply": false,
        "module": 1,
    },
    "d25": {
        "name": "——学生荣誉称号加减分",
        "limit": 1e6,
        "apply": true,
        "module": 1,
    },
    "z": {
        "name": "智育素质",
        "limit": 60,
        "apply": false,
        "module": 2,
    },
    "z1": {
        "name": "—智育平均学分绩点",
        "limit": 60,
        "apply": false,
        "module": 2,
    },
    "t": {
        "name": "体育素质",
        "limit": 8,
        "apply": false,
        "module": 3,
    },
    "t1": {
        "name": "—体育课程成绩T1",
        "limit": 5,
        "apply": false,
        "module": 3,
    },
    "t2": {
        "name": "—课外体育活动成绩T2",
        "limit": 3,
        "apply": false,
        "module": 3,
    },
    "t21": {
        "name": "——体育竞赛获奖得分",
        "limit": 2,
        "apply": true,
        "module": 3,
    },
    "t22": {
        "name": "——早锻炼得分",
        "limit": 1,
        "apply": false,
        "module": 3,
    },
    "m": {
        "name": "美育素质",
        "limit": 5,
        "apply": false,
        "module": 4,
    },
    "m1": {
        "name": "—文化艺术实践成绩M1",
        "limit": 0.5,
        "apply": true,
        "module": 4,
    },
    "m2": {
        "name": "—文化艺术竞赛获奖得分M2",
        "limit": 4.5,
        "apply": true,
        "module": 4,
    },
    "l": {
        "name": "劳育素质",
        "limit": 5,
        "apply": false,
        "module": 5,
    },
    "l1": {
        "name": "—日常劳动分L1",
        "limit": 1e6,
        "apply": false,
        "module": 5,
    },
    "l11": {
        "name": "——寝室日常考核基本分",
        "limit": 2,
        "apply": false,
        "module": 5,
    },
    "l12": {
        "name": "——“文明寝室”创建、寝室风采展等活动加分",
        "limit": 1e6,
        "apply": true,
        "module": 5,
    },
    "l13": {
        "name": "——寝室行为表现与卫生状况加减分",
        "limit": 1e6,
        "apply": false,
        "module": 5,
    },
    "l2": {
        "name": "—志愿服务分L2",
        "limit": 4,
        "apply": false,
        "module": 5,
    },
    "l3":{
        "name": "—实习实训L3",
        "limit": 1e6,
        "apply": false,
        "module": 5,
    },
    "c": {
        "name": "创新与实践素质",
        "limit": 12,
        "apply": false,
        "module": 6,
    },
    "c1": {
        "name": "—创新创业成绩C1",
        "limit": 1e6,
        "apply": false,
        "module": 6,
    },
    "c11": {
        "name": "——创新创业竞赛获奖得分",
        "limit": 1e6,
        "apply": true,
        "module": 6,
    },
    "c12": {
        "name": "——水平等级考试",
        "limit": 1e6,
        "apply": true,
        "module": 6,
    },
    "c2": {
        "name": "—社会实践活动C2",
        "limit": 1e6,
        "apply": true,
        "module": 6,
    },
    "c3": {
        "name": "—社会工作C3",
        "limit": 1e6,
        "apply": false,
        "module": 6,
    },
}